services:
  - type: web
    name: cro-agent
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false

