services:
  - type: web
    name: landing-page-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "python app.py"
    plan: free
